services:
  database:
    image: postgres:18

    container_name: fitness_tracker_db

    environment:
      POSTGRES_USER: fitnessadmin
      POSTGRES_PASSWORD: fitnesspass
      POSTGRES_DB: fitnesstracker

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: