CREATE TABLE IF NOT EXISTS workout_log (
    workout_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_name     VARCHAR(100) NOT NULL,
    workout_date     DATE NOT NULL,
    duration_minutes INTEGER NOT NULL,
    calories_burned  NUMERIC(10, 1) NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chk_workout_name_not_blank CHECK (length(btrim(workout_name)) > 0),
    CONSTRAINT chk_duration_range CHECK (duration_minutes BETWEEN 1 AND 480),
    CONSTRAINT chk_calories_nonnegative CHECK (calories_burned >= 0)
);

CREATE INDEX IF NOT EXISTS idx_workout_log_date ON workout_log (workout_date DESC, workout_id DESC);

CREATE OR REPLACE FUNCTION log_workout(
    p_workout_name TEXT,
    p_workout_date DATE,
    p_duration_minutes INTEGER,
    p_calories_burned NUMERIC DEFAULT 0
)
RETURNS workout_log
LANGUAGE plpgsql
AS $$
DECLARE
    saved workout_log;
BEGIN
    IF p_workout_name IS NULL OR length(btrim(p_workout_name)) = 0 THEN
        RAISE EXCEPTION 'Add a name for this workout.' USING ERRCODE = 'FT002';
    END IF;
    IF p_duration_minutes IS NULL OR p_duration_minutes NOT BETWEEN 1 AND 480 THEN
        RAISE EXCEPTION 'Duration must be between 1 and 480 minutes.' USING ERRCODE = 'FT001';
    END IF;
    IF p_calories_burned IS NULL OR p_calories_burned < 0 THEN
        RAISE EXCEPTION 'Calories must be zero or greater.' USING ERRCODE = 'FT003';
    END IF;

    INSERT INTO workout_log (workout_name, workout_date, duration_minutes, calories_burned)
    VALUES (btrim(p_workout_name), p_workout_date, p_duration_minutes, p_calories_burned)
    RETURNING * INTO saved;

    RETURN saved;
EXCEPTION
    WHEN not_null_violation THEN
        RAISE EXCEPTION 'A required workout field is missing.' USING ERRCODE = 'FT004';
END;
$$;

CREATE OR REPLACE FUNCTION current_week_summary()
RETURNS TABLE (
    session_count BIGINT,
    total_minutes BIGINT,
    average_minutes NUMERIC,
    total_calories NUMERIC
)
LANGUAGE SQL
STABLE
AS $$
    SELECT
        count(*)::BIGINT,
        coalesce(sum(duration_minutes), 0)::BIGINT,
        coalesce(round(avg(duration_minutes), 1), 0),
        coalesce(round(sum(calories_burned), 1), 0)
    FROM workout_log
    WHERE workout_date >= date_trunc('week', CURRENT_DATE)::DATE
      AND workout_date < (date_trunc('week', CURRENT_DATE) + INTERVAL '1 week')::DATE;
$$;
